"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { Activity, AppState, Conclusion, DailyLog, InternshipPlan } from "../lib/models";
import { getComplianceItems, getProgress } from "../lib/progress";
import { resetState } from "../lib/storage";

export type View = "dashboard" | "logs" | "plan" | "activities" | "conclusion" | "references" | "appendices" | "preview" | "compliance" | "settings";
const nav: { view: View; href: string; label: string; icon: string }[] = [
  { view: "dashboard", href: "/", label: "Tổng quan", icon: "⌂" }, { view: "logs", href: "/nhat-ky", label: "Nhật ký hằng ngày", icon: "✎" },
  { view: "plan", href: "/ke-hoach", label: "Kế hoạch thực tập", icon: "▦" }, { view: "activities", href: "/hoat-dong", label: "Hoạt động chính", icon: "◇" },
  { view: "conclusion", href: "/ket-luan", label: "Kết luận", icon: "✓" }, { view: "references", href: "/tai-lieu-tham-khao", label: "Tài liệu tham khảo", icon: "≡" },
  { view: "appendices", href: "/phu-luc", label: "Phụ lục", icon: "⊞" }, { view: "preview", href: "/xem-truoc", label: "Xem trước", icon: "◉" },
  { view: "compliance", href: "/kiem-tra", label: "Kiểm tra yêu cầu", icon: "☑" }, { view: "settings", href: "/cai-dat", label: "Cài đặt", icon: "⚙" },
];
const uid = () => crypto.randomUUID(), iso = () => new Date().toISOString(), today = () => new Date().toISOString().slice(0, 10);
const ACCESS_KEY_SESSION = "intern-diary:access-key";
type SaveStatus = "loading" | "locked" | "saving" | "saved" | "error";

async function requestCloudState(accessKey: string) {
  const response = await fetch("/api/state", { headers: { Authorization: `Bearer ${accessKey}` }, cache: "no-store" });
  const data = await response.json() as { state?: AppState; error?: string };
  if (!response.ok || !data.state) throw new Error(data.error || "Không thể mở dữ liệu.");
  return data.state;
}

async function persistCloudState(accessKey: string, state: AppState) {
  const response = await fetch("/api/state", {
    method: "PUT",
    headers: { Authorization: `Bearer ${accessKey}`, "Content-Type": "application/json" },
    body: JSON.stringify({ state }),
  });
  const data = await response.json() as { error?: string };
  if (!response.ok) throw new Error(data.error || "Không thể lưu dữ liệu.");
}

export default function InternshipApp({ view }: { view: View }) {
  const [state, setState] = useState<AppState | null>(null), [status, setStatus] = useState<SaveStatus>("loading"), [menu, setMenu] = useState(false), [accessInput, setAccessInput] = useState(""), [message, setMessage] = useState("");
  const accessKey = useRef(""), skipInitialSave = useRef(true);
  const unlock = async (key: string) => {
    setStatus("loading"); setMessage("");
    try {
      const cloudState = await requestCloudState(key);
      accessKey.current = key;
      sessionStorage.setItem(ACCESS_KEY_SESSION, key);
      skipInitialSave.current = true;
      setState(cloudState);
      setStatus("saved");
    } catch (error) {
      setState(null); setStatus("locked"); setMessage(error instanceof Error ? error.message : "Không thể mở dữ liệu.");
    }
  };
  useEffect(() => {
    const key = sessionStorage.getItem(ACCESS_KEY_SESSION);
    if (!key) { queueMicrotask(() => setStatus("locked")); return; }
    queueMicrotask(() => { void unlock(key); });
  }, []);
  useEffect(() => {
    if (!state || !accessKey.current) return;
    if (skipInitialSave.current) { skipInitialSave.current = false; return; }
    const timer = setTimeout(() => {
      setStatus("saving");
      void persistCloudState(accessKey.current, state).then(() => setStatus("saved")).catch(error => { setStatus("error"); setMessage(error instanceof Error ? error.message : "Không thể lưu dữ liệu."); });
    }, 700);
    return () => clearTimeout(timer);
  }, [state]);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (status === "saving") e.preventDefault(); }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [status]);
  if (status === "locked") return <div className="access-page"><form className="access-card" onSubmit={e => { e.preventDefault(); if (accessInput.trim()) void unlock(accessInput.trim()); }}><span className="brand-mark">N</span><small>NHẬT KÝ THỰC TẬP UEH</small><h1>Mở dữ liệu trên Vercel</h1><p>Nhập mã truy cập cá nhân. Nội dung nhật ký được lưu trên đám mây, không lưu trong bộ nhớ trình duyệt.</p><label><span>Mã truy cập</span><input type="password" autoComplete="current-password" value={accessInput} onChange={e => setAccessInput(e.target.value)} required /></label>{message && <div className="access-error">{message}</div>}<button className="primary-btn">Mở nhật ký</button></form></div>;
  if (!state) return <div className="loading">Đang tải dữ liệu từ Vercel…</div>;
  const update = (fn: (s: AppState) => AppState) => setState(previous => previous ? fn(previous) : previous);
  return <div className="app-shell"><aside className={menu ? "sidebar open" : "sidebar"}>
    <Link className="brand" href="/"><span className="brand-mark">N</span><span><b>Nhật ký thực tập</b><small>UEH · KIỂM TOÁN 2026</small></span></Link>
    <nav>{nav.map(item => <Link key={item.view} href={item.href} className={view === item.view ? "active" : ""}><span>{item.icon}</span>{item.label}{item.view === "compliance" && <em>{getComplianceItems(state).filter(item => item.status === "Đạt").length}</em>}</Link>)}</nav>
    <div className="sidebar-foot"><span>●</span><div><b>Đám mây riêng tư</b><small>Tự động lưu trên Vercel</small></div></div>
  </aside>{menu && <button className="scrim" onClick={() => setMenu(false)} aria-label="Đóng menu" />}
  <main><header className="topbar"><button className="menu-btn" onClick={() => setMenu(true)} aria-label="Mở trình đơn">☰</button><div className="crumb">Không gian làm việc <span>/</span> {nav.find(n => n.view === view)?.label}</div><div className={status === "saved" ? "save saved" : status === "error" ? "save error" : "save"}><i />{status === "saved" ? "Đã lưu trên Vercel" : status === "error" ? "Lỗi lưu dữ liệu" : "Đang lưu…"}</div><button className="avatar" aria-label="Tài khoản sinh viên">SV</button></header>
  <div className="security-banner"><span>⌾</span><p><b>Lưu ý bảo mật:</b> Không nhập tên khách hàng, số chứng từ hoặc thông tin mật. Hãy dùng “Công ty A”, “Nhân viên A” và mã giả.</p></div>
  <div className="page">{view === "dashboard" && <Dashboard state={state} />}{view === "logs" && <Logs state={state} update={update} />}{view === "plan" && <Plan state={state} update={update} />}{view === "activities" && <Activities state={state} update={update} />}{view === "conclusion" && <ConclusionView state={state} update={update} />}{view === "compliance" && <Compliance state={state} />}{view === "settings" && <Settings state={state} setState={setState} />}{["references", "appendices", "preview"].includes(view) && <Soon view={view} />}</div></main></div>;
}

function Title({ eyebrow, title, desc, action }: { eyebrow?: string; title: string; desc: string; action?: React.ReactNode }) { return <div className="page-title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{desc}</p></div>{action}</div>; }
function Dashboard({ state }: { state: AppState }) {
  const [currentTime] = useState(() => Date.now());
  const week = Math.min(12, Math.max(1, Math.ceil((currentTime - new Date(state.internship.startDate).getTime()) / 604800000)));
  const progress = getProgress(state), checks = getComplianceItems(state), reached = checks.filter(item => item.status === "Đạt").length;
  return <><Title eyebrow="THỰC TẬP TỐT NGHIỆP" title={`Xin chào, ${state.profile.fullName} 👋`} desc="Theo dõi tiến độ và hoàn thiện nhật ký thực tập của bạn." action={<Link className="primary-btn" href="/nhat-ky">＋ Thêm nhật ký</Link>} />
  <section className="hero"><div className="ring" style={{ "--p": `${progress.overall * 3.6}deg` } as React.CSSProperties}><span>{progress.overall}<small>%</small></span></div><div><small>TIẾN ĐỘ TỔNG THỂ</small><h2>Bạn đang đi đúng hướng</h2><p>Tiếp tục cập nhật nhật ký hằng ngày để hệ thống tổng hợp chính xác.</p><div className="milestones"><span className={progress.planComplete === 12 ? "done" : "current"}>1 Kế hoạch</span><span className={state.activities.length >= 3 ? "done" : "current"}>2 Hoạt động chính</span><span className={progress.conclusionFields === 8 ? "done" : "current"}>3 Kết luận</span></div></div><div className="week-card"><small>TUẦN HIỆN TẠI</small><strong>{week}<em>/12</em></strong><div><span style={{ width: `${week / 12 * 100}%` }} /></div><p>{Math.max(0, 12 - week)} tuần còn lại</p></div></section>
  <section className="stats"><Stat icon="▤" value={state.dailyLogs.length} label="Ngày đã ghi nhật ký" note="Dữ liệu thực tế đã lưu" /><Stat icon="◇" value={state.activities.length} label="Hoạt động chính" note={`${Math.max(0, 3 - state.activities.length)} hoạt động nữa để đạt yêu cầu`} /><Stat icon="▦" value={progress.totalPages} label="Trang ước tính" note="Ước tính 500 từ mỗi trang" /><Stat icon="☑" value={`${reached}/${checks.length}`} label="Yêu cầu đã đạt" note="Cần tự kiểm tra trước khi nộp" /></section>
  <section className="dashboard-grid"><div className="panel"><Head title="Tiến độ các phần" sub="Dựa trên nội dung bạn đã nhập" /><Progress no="01" title="Kế hoạch thực tập" value={Math.round(progress.planComplete / 12 * 100)} /><Progress no="02" title="Báo cáo hoạt động chính" value={Math.round(Math.min(100, state.activities.length / 3 * 100))} tone="orange" /><Progress no="03" title="Kết luận" value={Math.round(progress.conclusionFields / 8 * 100)} tone="purple" /></div><div className="panel"><Head title="Việc cần làm tiếp theo" sub="Ưu tiên để hoàn thiện hồ sơ" /><Task done={progress.planComplete === 12} text="Hoàn thiện kế hoạch 12 tuần" sub={`${progress.planComplete}/12 tuần đã đủ nội dung`} href="/ke-hoach" /><Task done={state.activities.length >= 3} text="Tạo ít nhất 3 hoạt động chính" sub={`${state.activities.length}/3 hoạt động`} href="/hoat-dong" /><Task done={!!state.conclusion.lessons} text="Bổ sung bài học kinh nghiệm" sub="Phần 3 · Kết luận" href="/ket-luan" /></div></section></>;
}
function Stat({ icon, value, label, note }: { icon: string; value: string | number; label: string; note: string }) { return <div className="stat"><span>{icon}</span><strong>{value}</strong><b>{label}</b><small>{note}</small></div>; }
function Head({ title, sub }: { title: string; sub: string }) { return <div className="panel-head"><h3>{title}</h3><p>{sub}</p></div>; }
function Progress({ no, title, value, tone = "green" }: { no: string; title: string; value: number; tone?: string }) { return <div className="progress"><span className={tone}>{no}</span><div><b>{title}</b><i><em className={tone} style={{ width: `${value}%` }} /></i></div><strong>{value}%</strong></div>; }
function Task({ done, text, sub, href }: { done: boolean; text: string; sub: string; href: string }) { return <Link className="task" href={href}><span className={done ? "done" : ""}>{done ? "✓" : ""}</span><div><b>{text}</b><small>{sub}</small></div><em>›</em></Link>; }

function Logs({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const [query, setQuery] = useState(""), [week, setWeek] = useState(0), [workType, setWorkType] = useState(""), [editing, setEditing] = useState<DailyLog | null>(null);
  const workTypes = Array.from(new Set(state.dailyLogs.map(log => log.workType).filter(Boolean))).sort((a, b) => a.localeCompare(b, "vi"));
  const filtered = state.dailyLogs.filter(l => (!week || l.week === week) && (!workType || l.workType === workType) && `${l.title} ${l.assignedWork} ${l.tags.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase()));
  const blank = (): DailyLog => ({ id: uid(), internshipId: state.internship.id, date: today(), week: 1, title: "", assignedWork: "", actionsTaken: "", relatedDocuments: "", tools: "", appliedKnowledge: "", result: "", difficulties: "", resolution: "", lessonsLearned: "", additionalNotes: "", workType: "", tags: [], files: [], sensitive: false, createdAt: iso(), updatedAt: iso() });
  const save = (log: DailyLog) => update(s => ({ ...s, dailyLogs: s.dailyLogs.some(x => x.id === log.id) ? s.dailyLogs.map(x => x.id === log.id ? { ...log, updatedAt: iso() } : x) : [{ ...log, updatedAt: iso() }, ...s.dailyLogs] }));
  return <><Title eyebrow="DỮ LIỆU THỰC TẾ" title="Nhật ký hằng ngày" desc="Ghi lại sự kiện đúng như bạn đã thực hiện; hệ thống sẽ dùng chúng cho báo cáo." action={<button className="primary-btn" onClick={() => setEditing(blank())}>＋ Thêm nhật ký</button>} />
  <div className="toolbar"><label className="search">⌕<input aria-label="Tìm nhật ký" value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm công việc hoặc thẻ…" /></label><select aria-label="Lọc theo tuần" value={week} onChange={e => setWeek(+e.target.value)}><option value={0}>Tất cả 12 tuần</option>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>Tuần {i + 1}</option>)}</select><select aria-label="Lọc theo loại công việc" value={workType} onChange={e => setWorkType(e.target.value)}><option value="">Mọi loại công việc</option>{workTypes.map(type => <option key={type}>{type}</option>)}</select><span>{filtered.length} bản ghi</span></div>
  <div className="log-list">{filtered.map(log => <article className="log-card" key={log.id}><div className="date"><b>{new Date(log.date).getDate()}</b><span>TH{new Date(log.date).getMonth() + 1}</span></div><div className="log-body"><small>TUẦN {log.week} · {log.workType || "CHƯA PHÂN LOẠI"}</small><h3>{log.title}</h3><p>{log.actionsTaken || log.assignedWork}</p><div className="tags">{log.tags.map(t => <span key={t}>{t}</span>)}{log.sensitive && <span className="sensitive">Nhạy cảm</span>}</div></div><div className="card-actions"><button onClick={() => setEditing(log)}>Sửa</button><button onClick={() => setEditing({ ...log, id: uid(), title: `${log.title} (bản sao)`, createdAt: iso() })}>Nhân bản</button><button className="danger" onClick={() => confirm("Xoá nhật ký này?") && update(s => ({ ...s, dailyLogs: s.dailyLogs.filter(x => x.id !== log.id), activities: s.activities.map(a => ({ ...a, dailyLogIds: a.dailyLogIds.filter(id => id !== log.id) })) }))}>Xoá</button></div></article>)}{!filtered.length && <Empty text="Chưa có nhật ký phù hợp bộ lọc." />}</div>
  {editing && <LogModal log={editing} onClose={() => setEditing(null)} onSave={log => { save(log); setEditing(null); }} />}</>;
}
function LogModal({ log, onClose, onSave }: { log: DailyLog; onClose: () => void; onSave: (l: DailyLog) => void }) {
  const [form, setForm] = useState(log), set = (key: keyof DailyLog, value: unknown) => setForm(f => ({ ...f, [key]: value }));
  const fields: [keyof DailyLog, string][] = [["assignedWork", "Mô tả ngắn công việc được giao"], ["actionsTaken", "Tôi đã thực hiện những gì"], ["relatedDocuments", "File / chứng từ / tài liệu liên quan"], ["tools", "Công cụ / phần mềm sử dụng"], ["appliedKnowledge", "Kiến thức hoặc kỹ năng áp dụng"], ["result", "Kết quả"], ["difficulties", "Khó khăn gặp phải"], ["resolution", "Cách xử lý"], ["lessonsLearned", "Điều học được"], ["additionalNotes", "Ghi chú thêm"]];
  return <Modal title={log.title ? "Chỉnh sửa bản ghi" : "Thêm nhật ký mới"} onClose={onClose} onSubmit={() => form.title.trim() && onSave({ ...form, title: form.title.trim(), tags: Array.from(new Set(form.tags.map(tag => tag.trim()).filter(Boolean))) })} footer="Tự động lưu trên Vercel sau khi xác nhận"><div className="form-grid"><Field label="Ngày"><input type="date" value={form.date} onChange={e => set("date", e.target.value)} required /></Field><Field label="Tuần thực tập"><select value={form.week} onChange={e => set("week", +e.target.value)}>{Array.from({ length: 12 }, (_, i) => <option key={i}>{i + 1}</option>)}</select></Field><Field label="Tên công việc" wide><input value={form.title} onChange={e => set("title", e.target.value)} required placeholder="Ví dụ: Kiểm tra chứng từ TK 152" /></Field><Field label="Loại công việc"><input value={form.workType} onChange={e => set("workType", e.target.value)} /></Field><Field label="Thẻ (cách nhau bằng dấu phẩy)"><input value={form.tags.join(", ")} onChange={e => set("tags", e.target.value.split(",").map(x => x.trim()).filter(Boolean))} /></Field>{fields.map(([key, label]) => <Field key={key} label={label} wide><textarea value={String(form[key] ?? "")} onChange={e => set(key, e.target.value)} rows={2} /></Field>)}<Sensitive checked={form.sensitive} onChange={v => set("sensitive", v)} /></div></Modal>;
}

function Plan({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const setPlan = (id: string, key: keyof InternshipPlan, value: string) => update(s => ({ ...s, plans: s.plans.map(p => p.id === id ? { ...p, [key]: value } : p), conclusion: { ...s.conclusion, rows: s.conclusion.rows.map(r => { const p = s.plans.find(x => x.id === id); return p?.week === r.week ? { ...r, ...(key === "target" ? { plannedTarget: value } : {}), ...(key === "workContent" ? { plannedWork: value } : {}) } : r; }) } }));
  return <><Title eyebrow="PHẦN 1" title="Kế hoạch thực tập" desc="Kế hoạch được giữ nguyên để đối chiếu với kết quả thực tế, không tự ghi đè." action={<span className="status-pill">{state.plans.filter(p => p.workContent).length}/12 tuần</span>} /><div className="table-wrap"><table><thead><tr><th>Tuần</th><th>Nội dung công việc</th><th>Mục tiêu cần đạt</th><th>Phương pháp sử dụng</th><th>Yêu cầu hỗ trợ</th><th>Yêu cầu kết quả</th></tr></thead><tbody>{state.plans.map(p => <tr key={p.id}><th>{p.week}</th>{(["workContent", "target", "method", "supportRequired", "expectedResult"] as (keyof InternshipPlan)[]).map(key => <td key={key}><textarea value={String(p[key])} onChange={e => setPlan(p.id, key, e.target.value)} placeholder="Nhập nội dung…" /></td>)}</tr>)}</tbody></table></div></>;
}

function Activities({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const [selected, setSelected] = useState<string[]>([]), [editing, setEditing] = useState<Activity | null>(null);
  const blank = (): Activity => ({ id: uid(), internshipId: state.internship.id, name: "", startDate: "", endDate: "", dailyLogIds: selected, objective: "", method: "Trải nghiệm thực tế", actualProcess: "", companyProcedures: "", workingPapers: "", recordsUsed: "", recordStorage: "", directSteps: "", result: "", difficulties: "", resolution: "", knowledgeAndSkills: "", appendixIds: [], sensitive: false, createdAt: iso(), updatedAt: iso() });
  const save = (a: Activity) => update(s => ({ ...s, activities: s.activities.some(x => x.id === a.id) ? s.activities.map(x => x.id === a.id ? { ...a, updatedAt: iso() } : x) : [...s.activities, { ...a, updatedAt: iso() }] }));
  return <><Title eyebrow="PHẦN 2 · TỐI THIỂU 3 HOẠT ĐỘNG" title="Hoạt động chính" desc="Chọn các bản ghi nhật ký liên quan rồi gom thành một hoạt động có thể truy vết." action={<button className="primary-btn" onClick={() => setEditing(blank())}>＋ Tạo hoạt động</button>} />
  <div className="activity-layout"><aside className="picker"><h3>Chọn bản ghi nhật ký</h3><p>{selected.length} bản ghi đã chọn</p>{state.dailyLogs.map(l => <label key={l.id}><input aria-label={`Chọn ${l.title}`} type="checkbox" checked={selected.includes(l.id)} onChange={e => setSelected(v => e.target.checked ? Array.from(new Set([...v, l.id])) : v.filter(x => x !== l.id))} /><span><b>{l.title}</b><small>Tuần {l.week} · {l.date}</small></span></label>)}<button className="secondary-btn" disabled={!selected.length} onClick={() => setEditing(blank())}>Gom thành hoạt động ({selected.length})</button></aside><div className="activity-list">{state.activities.map((a, i) => <article className="activity-card" key={a.id}><span>{String(i + 1).padStart(2, "0")}</span><div><small>{a.startDate || "Chưa có ngày"} — {a.endDate || "Chưa có ngày"}</small><h3>{a.name}</h3><p>{a.objective || "Chưa nhập mục tiêu hoạt động."}</p><div className="tags"><span>{a.method}</span><span>{a.dailyLogIds.length} bản ghi</span></div></div><div className="card-actions"><button className="ghost-btn" onClick={() => setEditing(a)}>Chỉnh sửa</button><button className="danger" onClick={() => confirm("Xoá hoạt động này?") && update(s => ({ ...s, activities: s.activities.filter(item => item.id !== a.id) }))}>Xoá</button></div></article>)}{!state.activities.length && <Empty text="Chưa có hoạt động chính. Chọn nhật ký bên trái để bắt đầu." />}</div></div>
  {editing && <ActivityModal activity={editing} logs={state.dailyLogs} onClose={() => setEditing(null)} onSave={a => { save(a); setSelected([]); setEditing(null); }} />}</>;
}
function ActivityModal({ activity, logs, onClose, onSave }: { activity: Activity; logs: DailyLog[]; onClose: () => void; onSave: (a: Activity) => void }) {
  const [form, setForm] = useState(activity), set = (key: keyof Activity, value: unknown) => setForm(f => ({ ...f, [key]: value }));
  const fields: [keyof Activity, string][] = [["objective", "Mục tiêu hoạt động"], ["actualProcess", "Quy trình thực hiện thực tế"], ["companyProcedures", "Quy định / quy trình công ty liên quan"], ["workingPapers", "Giấy làm việc sử dụng"], ["recordsUsed", "Hồ sơ / chứng từ sử dụng"], ["recordStorage", "Cách lưu hồ sơ"], ["directSteps", "Các bước tôi trực tiếp thực hiện"], ["result", "Kết quả đạt được"], ["difficulties", "Khó khăn"], ["resolution", "Cách xử lý"], ["knowledgeAndSkills", "Kiến thức / kỹ năng học được"]];
  return <Modal title={activity.name ? "Chỉnh sửa hoạt động" : "Tạo từ nhật ký"} onClose={onClose} onSubmit={() => form.name.trim() && onSave({ ...form, name: form.name.trim() })} footer="Phụ lục sẽ được liên kết ở giai đoạn 2"><div className="form-grid"><Field label="Tên hoạt động" wide><input value={form.name} onChange={e => set("name", e.target.value)} required /></Field><Field label="Từ ngày"><input type="date" value={form.startDate} onChange={e => set("startDate", e.target.value)} /></Field><Field label="Đến ngày"><input type="date" value={form.endDate} onChange={e => set("endDate", e.target.value)} /></Field><Field label="Phương pháp" wide><select value={form.method} onChange={e => set("method", e.target.value)}><option>Trải nghiệm thực tế</option><option>Tự nghiên cứu và đúc kết</option><option>Phương pháp khác</option></select></Field><Field label="Bản ghi nhật ký liên quan" wide><div className="log-options">{logs.map(log => <label key={log.id}><input type="checkbox" checked={form.dailyLogIds.includes(log.id)} onChange={e => set("dailyLogIds", e.target.checked ? Array.from(new Set([...form.dailyLogIds, log.id])) : form.dailyLogIds.filter(id => id !== log.id))} /><span>{log.title}</span></label>)}</div></Field>{fields.map(([key, label]) => <Field key={key} label={label} wide><textarea rows={2} value={String(form[key] ?? "")} onChange={e => set(key, e.target.value)} /></Field>)}<Sensitive checked={form.sensitive} onChange={v => set("sensitive", v)} /></div></Modal>;
}

function ConclusionView({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const set = (key: keyof Conclusion, value: string) => update(s => ({ ...s, conclusion: { ...s.conclusion, [key]: value, updatedAt: iso() } }));
  const setRow = (week: number, key: "actualTarget" | "actualWork" | "limitations" | "correctiveSolution" | "solutionExecution", value: string) => update(s => ({ ...s, conclusion: { ...s.conclusion, updatedAt: iso(), rows: s.conclusion.rows.map(row => row.week === week ? { ...row, [key]: value } : row) } }));
  const fields: [keyof Conclusion, string, string][] = [["completedWork", "Những công việc đã thực hiện", "Tóm tắt các nhóm công việc nổi bật…"], ["professionalKnowledge", "Kiến thức chuyên môn đã học được", "Liên hệ kiến thức kiểm toán đã áp dụng…"], ["developedSkills", "Kỹ năng đã phát triển", "Excel, giao tiếp, quản lý hồ sơ…"], ["lessons", "Bài học kinh nghiệm", "Những đúc kết quan trọng…"], ["personalLimitations", "Hạn chế của bản thân", "Nêu cụ thể và trung thực…"], ["personalChanges", "Sự thay đổi sau kỳ thực tập", "Nhận thức, tác phong, định hướng…"], ["internshipValue", "Giá trị nhận được", "Giá trị chuyên môn và cá nhân…"], ["finalConclusion", "Kết luận", "Khép lại quá trình thực tập…"]];
  // Textarea được lồng trực tiếp trong label có nội dung hiển thị; luật lint không nhận diện cấu trúc rút gọn này.
  // eslint-disable-next-line jsx-a11y/label-has-associated-control
  return <><Title eyebrow="PHẦN 3 · TỐI THIỂU 5 TRANG" title="Kết luận" desc="Tổng kết dựa trên dữ liệu thực tế; bạn luôn là người duyệt nội dung cuối cùng." /><section className="panel summary"><h3>3.1. Tổng kết quá trình thực tập</h3><p>Kế hoạch được giữ nguyên; các cột thực tế, hạn chế và giải pháp có thể chỉnh sửa độc lập.</p><div className="table-wrap conclusion-table"><table><thead><tr><th>Tuần</th><th>Mục tiêu kế hoạch</th><th>Mục tiêu thực tế</th><th>Công việc kế hoạch</th><th>Công việc thực tế</th><th>Hạn chế</th><th>Giải pháp khắc phục</th><th>Kết quả thực hiện</th></tr></thead><tbody>{state.conclusion.rows.map(row => <tr key={row.week}><th>{row.week}</th><td>{row.plannedTarget || "Chưa có"}</td><td><textarea aria-label={`Mục tiêu thực tế tuần ${row.week}`} value={row.actualTarget} onChange={e => setRow(row.week, "actualTarget", e.target.value)} /></td><td>{row.plannedWork || "Chưa có"}</td><td><textarea aria-label={`Công việc thực tế tuần ${row.week}`} value={row.actualWork} onChange={e => setRow(row.week, "actualWork", e.target.value)} /></td><td><textarea aria-label={`Hạn chế tuần ${row.week}`} value={row.limitations} onChange={e => setRow(row.week, "limitations", e.target.value)} /></td><td><textarea aria-label={`Giải pháp tuần ${row.week}`} value={row.correctiveSolution} onChange={e => setRow(row.week, "correctiveSolution", e.target.value)} /></td><td><textarea aria-label={`Kết quả thực hiện tuần ${row.week}`} value={row.solutionExecution} onChange={e => setRow(row.week, "solutionExecution", e.target.value)} /></td></tr>)}</tbody></table></div></section><h2 className="section-title">3.2. Tổng kết kết quả thực tập</h2><section className="conclusion-grid">{fields.map(([key, label, placeholder]) => <label className="editor" key={key}><span><b>{label}</b><small>{String(state.conclusion[key] || "").length} ký tự</small></span><textarea rows={6} value={String(state.conclusion[key] ?? "")} onChange={e => set(key, e.target.value)} placeholder={placeholder} /></label>)}</section></>;
}
function Compliance({ state }: { state: AppState }) { const progress = getProgress(state), checks = getComplianceItems(state); return <><Title eyebrow="UEH 2026" title="Kiểm tra yêu cầu" desc="Công cụ hỗ trợ rà soát, không thay thế việc tự kiểm tra quy định trước khi nộp." /><div className="notice">⚠ Số trang được ước tính theo 500 từ mỗi trang: Phần 1 có {progress.part1Pages} trang, Phần 2 có {progress.part2Pages} trang, Phần 3 có {progress.part3Pages} trang. Trạng thái “Đạt” không đồng nghĩa hồ sơ đã được Khoa chấp thuận.</div><div className="checks">{checks.map(item => <div key={item.label}><span className={item.status === "Đạt" ? "ok" : "pending"}>{item.status === "Đạt" ? "✓" : item.status === "Cần kiểm tra" ? "?" : "!"}</span><b>{item.label}</b><em>{item.status}</em></div>)}</div></>; }
function Settings({ state, setState }: { state: AppState; setState: (s: AppState) => void }) { return <><Title eyebrow="CÁ NHÂN HOÁ" title="Cài đặt" desc="Quản lý dữ liệu trên Vercel và các nguyên tắc bảo mật." /><div className="settings"><section className="panel"><h3>Hồ sơ thực tập</h3><Field label="Họ và tên"><input value={state.profile.fullName} onChange={e => setState({ ...state, profile: { ...state.profile, fullName: e.target.value } })} /></Field><Field label="Đơn vị thực tập"><input value={state.internship.organization} onChange={e => setState({ ...state, internship: { ...state.internship, organization: e.target.value } })} /></Field></section><section className="panel"><h3>Dữ liệu trên Vercel</h3><p>Mọi thay đổi được tự động lưu vào kho Blob riêng tư trên Vercel. Trình duyệt không giữ bản sao nội dung nhật ký.</p><button className="secondary-btn" onClick={() => confirm("Thay dữ liệu hiện tại bằng dữ liệu minh hoạ?") && setState(resetState(true))}>Nạp dữ liệu minh hoạ</button><button className="danger-btn" onClick={() => confirm("Xoá toàn bộ nội dung nhật ký trên Vercel?") && setState(resetState(false))}>Xoá dữ liệu và bắt đầu trống</button></section></div></>; }
function Soon({ view }: { view: View }) { const names: Record<string, string> = { references: "Tài liệu tham khảo", appendices: "Phụ lục", preview: "Xem trước tài liệu" }; return <><Title eyebrow="GIAI ĐOẠN 2" title={names[view]} desc="Cấu trúc dữ liệu đã sẵn sàng; tính năng tài liệu sẽ được triển khai ở giai đoạn kế tiếp." /><div className="coming"><span>⌁</span><h2>Đã có trong lộ trình giai đoạn 2</h2><p>Bản xem trước A4, phần kiểm tra yêu cầu hoàn chỉnh, chức năng xuất Word và PDF sẽ dùng chung dữ liệu của giai đoạn 1.</p><Link href="/">Về Tổng quan</Link></div></>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? "field wide" : "field"}><span>{label}</span>{children}</label>; }
function Sensitive({ checked, onChange }: { checked: boolean; onChange: (v: boolean) => void }) { return <label className="sensitive-check wide"><input aria-label="Đánh dấu dữ liệu nhạy cảm" type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span><b>Đánh dấu dữ liệu nhạy cảm</b><small>Yêu cầu ẩn danh trước khi xuất hoặc dùng AI.</small></span></label>; }
function Empty({ text }: { text: string }) { return <div className="empty"><span>＋</span><p>{text}</p></div>; }
function Modal({ title, onClose, onSubmit, footer, children }: { title: string; onClose: () => void; onSubmit: () => void; footer: string; children: React.ReactNode }) { return <div className="modal-back"><form className="modal" onSubmit={e => { e.preventDefault(); onSubmit(); }}><div className="modal-head"><div><small>NHẬT KÝ THỰC TẬP</small><h2>{title}</h2></div><button type="button" onClick={onClose}>×</button></div>{children}<div className="modal-foot"><span>● {footer}</span><button type="button" className="ghost-btn" onClick={onClose}>Huỷ</button><button className="primary-btn">Lưu</button></div></form></div>; }
