"use client";

import { useEffect, useState } from "react";
import type { Activity, AppState, Conclusion, DailyLog, InternshipPlan } from "../lib/models";
import { loadState, resetState, saveState } from "../lib/storage";

export type View = "dashboard" | "logs" | "plan" | "activities" | "conclusion" | "references" | "appendices" | "preview" | "compliance" | "settings";
const nav: { view: View; href: string; label: string; icon: string }[] = [
  { view: "dashboard", href: "/", label: "Tổng quan", icon: "⌂" }, { view: "logs", href: "/nhat-ky", label: "Nhật ký hằng ngày", icon: "✎" },
  { view: "plan", href: "/ke-hoach", label: "Kế hoạch thực tập", icon: "▦" }, { view: "activities", href: "/hoat-dong", label: "Hoạt động chính", icon: "◇" },
  { view: "conclusion", href: "/ket-luan", label: "Kết luận", icon: "✓" }, { view: "references", href: "/tai-lieu-tham-khao", label: "Tài liệu tham khảo", icon: "≡" },
  { view: "appendices", href: "/phu-luc", label: "Phụ lục", icon: "⊞" }, { view: "preview", href: "/xem-truoc", label: "Xem trước", icon: "◉" },
  { view: "compliance", href: "/kiem-tra", label: "Kiểm tra yêu cầu", icon: "☑" }, { view: "settings", href: "/cai-dat", label: "Cài đặt", icon: "⚙" },
];
const uid = () => crypto.randomUUID(), iso = () => new Date().toISOString(), today = () => new Date().toISOString().slice(0, 10);

export default function InternshipApp({ view }: { view: View }) {
  const [state, setState] = useState<AppState | null>(null), [saved, setSaved] = useState(true), [menu, setMenu] = useState(false);
  useEffect(() => setState(loadState()), []);
  useEffect(() => { if (!state) return; setSaved(false); const timer = setTimeout(() => { saveState(state); setSaved(true); }, 450); return () => clearTimeout(timer); }, [state]);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (!saved) e.preventDefault(); }; addEventListener("beforeunload", warn); return () => removeEventListener("beforeunload", warn); }, [saved]);
  if (!state) return <div className="loading">Đang mở sổ nhật ký…</div>;
  const update = (fn: (s: AppState) => AppState) => setState(previous => previous ? fn(previous) : previous);
  return <div className="app-shell"><aside className={menu ? "sidebar open" : "sidebar"}>
    <a className="brand" href="/"><span className="brand-mark">N</span><span><b>Nhật ký thực tập</b><small>UEH · KIỂM TOÁN 2026</small></span></a>
    <nav>{nav.map(item => <a key={item.view} href={item.href} className={view === item.view ? "active" : ""}><span>{item.icon}</span>{item.label}{item.view === "compliance" && <em>7</em>}</a>)}</nav>
    <div className="sidebar-foot"><span>●</span><div><b>Chế độ riêng tư</b><small>Dữ liệu lưu trên thiết bị này</small></div></div>
  </aside>{menu && <button className="scrim" onClick={() => setMenu(false)} aria-label="Đóng menu" />}
  <main><header className="topbar"><button className="menu-btn" onClick={() => setMenu(true)}>☰</button><div className="crumb">Không gian làm việc <span>/</span> {nav.find(n => n.view === view)?.label}</div><div className={saved ? "save saved" : "save"}><i />{saved ? "Đã lưu" : "Đang lưu…"}</div><button className="avatar">SV</button></header>
  <div className="security-banner"><span>⌾</span><p><b>Lưu ý bảo mật:</b> Không nhập tên khách hàng, số chứng từ hoặc thông tin mật. Hãy dùng “Công ty A”, “Nhân viên A” và mã giả.</p></div>
  <div className="page">{view === "dashboard" && <Dashboard state={state} />}{view === "logs" && <Logs state={state} update={update} />}{view === "plan" && <Plan state={state} update={update} />}{view === "activities" && <Activities state={state} update={update} />}{view === "conclusion" && <ConclusionView state={state} update={update} />}{view === "compliance" && <Compliance state={state} />}{view === "settings" && <Settings state={state} setState={setState} />}{["references", "appendices", "preview"].includes(view) && <Soon view={view} />}</div></main></div>;
}

function Title({ eyebrow, title, desc, action }: { eyebrow?: string; title: string; desc: string; action?: React.ReactNode }) { return <div className="page-title"><div><small>{eyebrow}</small><h1>{title}</h1><p>{desc}</p></div>{action}</div>; }
function Dashboard({ state }: { state: AppState }) {
  const week = Math.min(12, Math.max(1, Math.ceil((Date.now() - new Date(state.internship.startDate).getTime()) / 604800000))), plan = state.plans.filter(p => p.workContent && p.target).length;
  const filled = [state.conclusion.completedWork, state.conclusion.professionalKnowledge, state.conclusion.developedSkills, state.conclusion.lessons, state.conclusion.finalConclusion].filter(Boolean).length;
  const overall = Math.round(Math.min(100, plan / 12 * 30 + Math.min(3, state.activities.length) / 3 * 40 + filled / 5 * 30));
  return <><Title eyebrow="THỰC TẬP TỐT NGHIỆP" title={`Chào buổi sáng, ${state.profile.fullName} 👋`} desc="Theo dõi tiến độ và hoàn thiện Nhật ký thực tập của bạn." action={<a className="primary-btn" href="/nhat-ky">＋ Thêm nhật ký</a>} />
  <section className="hero"><div className="ring" style={{ "--p": `${overall * 3.6}deg` } as React.CSSProperties}><span>{overall}<small>%</small></span></div><div><small>TIẾN ĐỘ TỔNG THỂ</small><h2>Bạn đang đi đúng hướng</h2><p>Tiếp tục cập nhật nhật ký hằng ngày để hệ thống tổng hợp chính xác.</p><div className="milestones"><span className="done">✓ Kế hoạch</span><span className="current">2 Hoạt động chính</span><span>3 Kết luận</span></div></div><div className="week-card"><small>TUẦN HIỆN TẠI</small><strong>{week}<em>/12</em></strong><div><span style={{ width: `${week / 12 * 100}%` }} /></div><p>{Math.max(0, 12 - week)} tuần còn lại</p></div></section>
  <section className="stats"><Stat icon="▤" value={state.dailyLogs.length} label="Ngày đã ghi nhật ký" note="Dữ liệu thực tế đã lưu" /><Stat icon="◇" value={state.activities.length} label="Hoạt động chính" note={`${Math.max(0, 3 - state.activities.length)} hoạt động nữa để đạt yêu cầu`} /><Stat icon="▦" value={Math.max(1, Math.ceil((state.dailyLogs.length * 220 + state.activities.length * 700 + filled * 250) / 450))} label="Trang ước tính" note="Mục tiêu nội dung chính ≥ 20" /><Stat icon="☑" value={`${Math.round(plan / 12 * 3 + Math.min(3, state.activities.length) + filled / 5 * 4)}/10`} label="Yêu cầu đã đạt" note="Cần tự kiểm tra trước khi nộp" /></section>
  <section className="dashboard-grid"><div className="panel"><Head title="Tiến độ các phần" sub="Dựa trên nội dung bạn đã nhập" /><Progress no="01" title="Kế hoạch thực tập" value={Math.round(plan / 12 * 100)} /><Progress no="02" title="Báo cáo hoạt động chính" value={Math.round(Math.min(100, state.activities.length / 3 * 100))} tone="orange" /><Progress no="03" title="Kết luận" value={Math.round(filled / 5 * 100)} tone="purple" /></div><div className="panel"><Head title="Việc cần làm tiếp theo" sub="Ưu tiên để hoàn thiện hồ sơ" /><Task done={plan === 12} text="Hoàn thiện kế hoạch 12 tuần" sub={`${plan}/12 tuần đã có nội dung`} href="/ke-hoach" /><Task done={state.activities.length >= 3} text="Tạo ít nhất 3 hoạt động chính" sub={`${state.activities.length}/3 hoạt động`} href="/hoat-dong" /><Task done={!!state.conclusion.lessons} text="Bổ sung bài học kinh nghiệm" sub="Phần 3 · Kết luận" href="/ket-luan" /></div></section></>;
}
function Stat({ icon, value, label, note }: { icon: string; value: string | number; label: string; note: string }) { return <div className="stat"><span>{icon}</span><strong>{value}</strong><b>{label}</b><small>{note}</small></div>; }
function Head({ title, sub }: { title: string; sub: string }) { return <div className="panel-head"><h3>{title}</h3><p>{sub}</p></div>; }
function Progress({ no, title, value, tone = "green" }: { no: string; title: string; value: number; tone?: string }) { return <div className="progress"><span className={tone}>{no}</span><div><b>{title}</b><i><em className={tone} style={{ width: `${value}%` }} /></i></div><strong>{value}%</strong></div>; }
function Task({ done, text, sub, href }: { done: boolean; text: string; sub: string; href: string }) { return <a className="task" href={href}><span className={done ? "done" : ""}>{done ? "✓" : ""}</span><div><b>{text}</b><small>{sub}</small></div><em>›</em></a>; }

function Logs({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const [query, setQuery] = useState(""), [week, setWeek] = useState(0), [editing, setEditing] = useState<DailyLog | null>(null);
  const filtered = state.dailyLogs.filter(l => (!week || l.week === week) && `${l.title} ${l.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const blank = (): DailyLog => ({ id: uid(), internshipId: state.internship.id, date: today(), week: 1, title: "", assignedWork: "", actionsTaken: "", relatedDocuments: "", tools: "", appliedKnowledge: "", result: "", difficulties: "", resolution: "", lessonsLearned: "", additionalNotes: "", workType: "", tags: [], files: [], sensitive: false, createdAt: iso(), updatedAt: iso() });
  const save = (log: DailyLog) => update(s => ({ ...s, dailyLogs: s.dailyLogs.some(x => x.id === log.id) ? s.dailyLogs.map(x => x.id === log.id ? { ...log, updatedAt: iso() } : x) : [{ ...log, updatedAt: iso() }, ...s.dailyLogs] }));
  return <><Title eyebrow="DỮ LIỆU THỰC TẾ" title="Nhật ký hằng ngày" desc="Ghi lại sự kiện đúng như bạn đã thực hiện; hệ thống sẽ dùng chúng cho báo cáo." action={<button className="primary-btn" onClick={() => setEditing(blank())}>＋ Thêm nhật ký</button>} />
  <div className="toolbar"><label className="search">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm công việc hoặc tag…" /></label><select value={week} onChange={e => setWeek(+e.target.value)}><option value={0}>Tất cả 12 tuần</option>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>Tuần {i + 1}</option>)}</select><span>{filtered.length} bản ghi</span></div>
  <div className="log-list">{filtered.map(log => <article className="log-card" key={log.id}><div className="date"><b>{new Date(log.date).getDate()}</b><span>TH{new Date(log.date).getMonth() + 1}</span></div><div className="log-body"><small>TUẦN {log.week} · {log.workType || "CHƯA PHÂN LOẠI"}</small><h3>{log.title}</h3><p>{log.actionsTaken || log.assignedWork}</p><div className="tags">{log.tags.map(t => <span key={t}>{t}</span>)}{log.sensitive && <span className="sensitive">Nhạy cảm</span>}</div></div><div className="card-actions"><button onClick={() => setEditing(log)}>Sửa</button><button onClick={() => setEditing({ ...log, id: uid(), title: `${log.title} (bản sao)`, createdAt: iso() })}>Nhân bản</button><button className="danger" onClick={() => confirm("Xoá nhật ký này?") && update(s => ({ ...s, dailyLogs: s.dailyLogs.filter(x => x.id !== log.id), activities: s.activities.map(a => ({ ...a, dailyLogIds: a.dailyLogIds.filter(id => id !== log.id) })) }))}>Xoá</button></div></article>)}{!filtered.length && <Empty text="Chưa có nhật ký phù hợp bộ lọc." />}</div>
  {editing && <LogModal log={editing} onClose={() => setEditing(null)} onSave={log => { save(log); setEditing(null); }} />}</>;
}
function LogModal({ log, onClose, onSave }: { log: DailyLog; onClose: () => void; onSave: (l: DailyLog) => void }) {
  const [form, setForm] = useState(log), set = (key: keyof DailyLog, value: unknown) => setForm(f => ({ ...f, [key]: value }));
  const fields: [keyof DailyLog, string][] = [["assignedWork", "Mô tả ngắn công việc được giao"], ["actionsTaken", "Tôi đã thực hiện những gì"], ["relatedDocuments", "File / chứng từ / tài liệu liên quan"], ["tools", "Công cụ / phần mềm sử dụng"], ["appliedKnowledge", "Kiến thức hoặc kỹ năng áp dụng"], ["result", "Kết quả"], ["difficulties", "Khó khăn gặp phải"], ["resolution", "Cách xử lý"], ["lessonsLearned", "Điều học được"], ["additionalNotes", "Ghi chú thêm"]];
  return <Modal title={log.title ? "Chỉnh sửa bản ghi" : "Thêm nhật ký mới"} onClose={onClose} onSubmit={() => form.title.trim() && onSave(form)} footer="Tự động lưu sau khi xác nhận"><div className="form-grid"><Field label="Ngày"><input type="date" value={form.date} onChange={e => set("date", e.target.value)} required /></Field><Field label="Tuần thực tập"><select value={form.week} onChange={e => set("week", +e.target.value)}>{Array.from({ length: 12 }, (_, i) => <option key={i}>{i + 1}</option>)}</select></Field><Field label="Tên công việc" wide><input value={form.title} onChange={e => set("title", e.target.value)} required placeholder="Ví dụ: Kiểm tra chứng từ TK 152" /></Field><Field label="Loại công việc"><input value={form.workType} onChange={e => set("workType", e.target.value)} /></Field><Field label="Tags (cách nhau bằng dấu phẩy)"><input value={form.tags.join(", ")} onChange={e => set("tags", e.target.value.split(",").map(x => x.trim()).filter(Boolean))} /></Field>{fields.map(([key, label]) => <Field key={key} label={label} wide><textarea value={String(form[key] ?? "")} onChange={e => set(key, e.target.value)} rows={2} /></Field>)}<Sensitive checked={form.sensitive} onChange={v => set("sensitive", v)} /></div></Modal>;
}

function Plan({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const setPlan = (id: string, key: keyof InternshipPlan, value: string) => update(s => ({ ...s, plans: s.plans.map(p => p.id === id ? { ...p, [key]: value } : p), conclusion: { ...s.conclusion, rows: s.conclusion.rows.map(r => { const p = s.plans.find(x => x.id === id); return p?.week === r.week ? { ...r, ...(key === "target" ? { plannedTarget: value } : {}), ...(key === "workContent" ? { plannedWork: value } : {}) } : r; }) } }));
  return <><Title eyebrow="PHẦN 1" title="Kế hoạch thực tập" desc="Kế hoạch được giữ nguyên để đối chiếu với kết quả thực tế, không tự ghi đè." action={<span className="status-pill">{state.plans.filter(p => p.workContent).length}/12 tuần</span>} /><div className="table-wrap"><table><thead><tr><th>Tuần</th><th>Nội dung công việc</th><th>Mục tiêu cần đạt</th><th>Phương pháp sử dụng</th><th>Yêu cầu hỗ trợ</th><th>Yêu cầu kết quả</th></tr></thead><tbody>{state.plans.map(p => <tr key={p.id}><th>{p.week}</th>{(["workContent", "target", "method", "supportRequired", "expectedResult"] as (keyof InternshipPlan)[]).map(key => <td key={key}><textarea value={String(p[key])} onChange={e => setPlan(p.id, key, e.target.value)} placeholder="Nhập nội dung…" /></td>)}</tr>)}</tbody></table></div></>;
}

function Activities({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const [selected, setSelected] = useState<string[]>([]), [editing, setEditing] = useState<Activity | null>(null);
  const blank = (): Activity => ({ id: uid(), internshipId: state.internship.id, name: "", startDate: "", endDate: "", dailyLogIds: selected, objective: "", method: "Trải nghiệm thực tế", actualProcess: "", companyProcedures: "", workingPapers: "", recordsUsed: "", recordStorage: "", directSteps: "", result: "", difficulties: "", resolution: "", knowledgeAndSkills: "", appendixIds: [], sensitive: false, createdAt: iso(), updatedAt: iso() });
  const save = (a: Activity) => update(s => ({ ...s, activities: s.activities.some(x => x.id === a.id) ? s.activities.map(x => x.id === a.id ? { ...a, updatedAt: iso() } : x) : [...s.activities, { ...a, updatedAt: iso() }] }));
  return <><Title eyebrow="PHẦN 2 · TỐI THIỂU 3 HOẠT ĐỘNG" title="Hoạt động chính" desc="Chọn các Daily Log liên quan rồi gom thành một hoạt động có thể truy vết." action={<button className="primary-btn" onClick={() => setEditing(blank())}>＋ Tạo hoạt động</button>} />
  <div className="activity-layout"><aside className="picker"><h3>Chọn Daily Log</h3><p>{selected.length} bản ghi đã chọn</p>{state.dailyLogs.map(l => <label key={l.id}><input type="checkbox" checked={selected.includes(l.id)} onChange={e => setSelected(v => e.target.checked ? [...v, l.id] : v.filter(x => x !== l.id))} /><span><b>{l.title}</b><small>Tuần {l.week} · {l.date}</small></span></label>)}<button className="secondary-btn" disabled={!selected.length} onClick={() => setEditing(blank())}>Gom thành hoạt động ({selected.length})</button></aside><div className="activity-list">{state.activities.map((a, i) => <article className="activity-card" key={a.id}><span>{String(i + 1).padStart(2, "0")}</span><div><small>{a.startDate || "Chưa có ngày"} — {a.endDate || "Chưa có ngày"}</small><h3>{a.name}</h3><p>{a.objective || "Chưa nhập mục tiêu hoạt động."}</p><div className="tags"><span>{a.method}</span><span>{a.dailyLogIds.length} Daily Log</span></div></div><button className="ghost-btn" onClick={() => setEditing(a)}>Chỉnh sửa</button></article>)}{!state.activities.length && <Empty text="Chưa có hoạt động chính. Chọn nhật ký bên trái để bắt đầu." />}</div></div>
  {editing && <ActivityModal activity={editing} logs={state.dailyLogs} onClose={() => setEditing(null)} onSave={a => { save(a); setSelected([]); setEditing(null); }} />}</>;
}
function ActivityModal({ activity, logs, onClose, onSave }: { activity: Activity; logs: DailyLog[]; onClose: () => void; onSave: (a: Activity) => void }) {
  const [form, setForm] = useState(activity), set = (key: keyof Activity, value: unknown) => setForm(f => ({ ...f, [key]: value }));
  const fields: [keyof Activity, string][] = [["objective", "Mục tiêu hoạt động"], ["actualProcess", "Quy trình thực hiện thực tế"], ["companyProcedures", "Quy định / quy trình công ty liên quan"], ["workingPapers", "Giấy làm việc sử dụng"], ["recordsUsed", "Hồ sơ / chứng từ sử dụng"], ["recordStorage", "Cách lưu hồ sơ"], ["directSteps", "Các bước tôi trực tiếp thực hiện"], ["result", "Kết quả đạt được"], ["difficulties", "Khó khăn"], ["resolution", "Cách xử lý"], ["knowledgeAndSkills", "Kiến thức / kỹ năng học được"]];
  return <Modal title={activity.name ? "Chỉnh sửa hoạt động" : "Tạo từ Daily Log"} onClose={onClose} onSubmit={() => form.name.trim() && onSave(form)} footer="Phụ lục sẽ được liên kết ở Phase 2"><div className="form-grid"><Field label="Tên hoạt động" wide><input value={form.name} onChange={e => set("name", e.target.value)} required /></Field><Field label="Từ ngày"><input type="date" value={form.startDate} onChange={e => set("startDate", e.target.value)} /></Field><Field label="Đến ngày"><input type="date" value={form.endDate} onChange={e => set("endDate", e.target.value)} /></Field><Field label="Phương pháp" wide><select value={form.method} onChange={e => set("method", e.target.value)}><option>Trải nghiệm thực tế</option><option>Tự nghiên cứu và đúc kết</option><option>Phương pháp khác</option></select></Field><Field label="Daily Log liên quan" wide><div className="selected-logs">{logs.filter(l => form.dailyLogIds.includes(l.id)).map(l => <span key={l.id}>{l.title}<button type="button" onClick={() => set("dailyLogIds", form.dailyLogIds.filter(id => id !== l.id))}>×</button></span>)}</div></Field>{fields.map(([key, label]) => <Field key={key} label={label} wide><textarea rows={2} value={String(form[key] ?? "")} onChange={e => set(key, e.target.value)} /></Field>)}<Sensitive checked={form.sensitive} onChange={v => set("sensitive", v)} /></div></Modal>;
}

function ConclusionView({ state, update }: { state: AppState; update: (fn: (s: AppState) => AppState) => void }) {
  const set = (key: keyof Conclusion, value: string) => update(s => ({ ...s, conclusion: { ...s.conclusion, [key]: value, updatedAt: iso() } }));
  const fields: [keyof Conclusion, string, string][] = [["completedWork", "Những công việc đã thực hiện", "Tóm tắt các nhóm công việc nổi bật…"], ["professionalKnowledge", "Kiến thức chuyên môn đã học được", "Liên hệ kiến thức kiểm toán đã áp dụng…"], ["developedSkills", "Kỹ năng đã phát triển", "Excel, giao tiếp, quản lý hồ sơ…"], ["lessons", "Bài học kinh nghiệm", "Những đúc kết quan trọng…"], ["personalLimitations", "Hạn chế của bản thân", "Nêu cụ thể và trung thực…"], ["personalChanges", "Sự thay đổi sau kỳ thực tập", "Nhận thức, tác phong, định hướng…"], ["internshipValue", "Giá trị nhận được", "Giá trị chuyên môn và cá nhân…"], ["finalConclusion", "Kết luận", "Khép lại quá trình thực tập…"]];
  return <><Title eyebrow="PHẦN 3 · TỐI THIỂU 5 TRANG" title="Kết luận" desc="Tổng kết dựa trên dữ liệu thực tế; bạn luôn là người duyệt nội dung cuối cùng." /><section className="panel summary"><h3>3.1. Tổng kết quá trình thực tập</h3><p>Bảng 12 tuần giữ riêng kế hoạch và kết quả thực tế.</p><div>{state.conclusion.rows.map(r => <article key={r.week}><b>Tuần {r.week}</b><span>{r.plannedWork || "Chưa có kế hoạch"}</span><em>{state.dailyLogs.filter(l => l.week === r.week).length} nhật ký thực tế</em></article>)}</div></section><h2 className="section-title">3.2. Tổng kết kết quả thực tập</h2><section className="conclusion-grid">{fields.map(([key, label, placeholder]) => <label className="editor" key={key}><span><b>{label}</b><small>{String(state.conclusion[key] || "").length} ký tự</small></span><textarea rows={6} value={String(state.conclusion[key] ?? "")} onChange={e => set(key, e.target.value)} placeholder={placeholder} /></label>)}</section></>;
}
function Compliance({ state }: { state: AppState }) { const pages = Math.max(1, Math.ceil((state.dailyLogs.length * 220 + state.activities.length * 700) / 450)); const checks: [string, boolean][] = [["Nội dung chính ≥ 20 trang", pages >= 20], ["Phần 2 ≥ 10 trang", state.activities.length >= 3 && pages >= 10], ["Có ≥ 3 hoạt động chính", state.activities.length >= 3], ["Phần 3 ≥ 5 trang", state.conclusion.finalConclusion.length > 1200], ["Có kế hoạch thực tập", state.plans.every(p => p.workContent)], ["Có bảng tổng kết thực tập", state.conclusion.rows.some(r => r.actualWork)], ["Có kết luận / bài học", !!state.conclusion.lessons && !!state.conclusion.finalConclusion], ["Có trang bìa", false], ["Có mục lục", false], ["Có danh mục từ viết tắt", false]]; return <><Title eyebrow="UEH 2026" title="Kiểm tra yêu cầu" desc="Công cụ hỗ trợ rà soát, không thay thế việc tự kiểm tra quy định trước khi nộp." /><div className="notice">⚠ Số trang chỉ là ước tính ở Phase 1. Trạng thái “Đạt” không đồng nghĩa hồ sơ đã được Khoa chấp thuận.</div><div className="checks">{checks.map(([label, ok]) => <div key={label}><span className={ok ? "ok" : "pending"}>{ok ? "✓" : "!"}</span><b>{label}</b><em>{ok ? "Đạt" : "Chưa đạt"}</em></div>)}</div></>; }
function Settings({ state, setState }: { state: AppState; setState: (s: AppState) => void }) { return <><Title eyebrow="CÁ NHÂN HOÁ" title="Cài đặt" desc="Quản lý dữ liệu lưu trên thiết bị và các nguyên tắc bảo mật." /><div className="settings"><section className="panel"><h3>Hồ sơ thực tập</h3><Field label="Họ và tên"><input value={state.profile.fullName} onChange={e => setState({ ...state, profile: { ...state.profile, fullName: e.target.value } })} /></Field><Field label="Đơn vị thực tập"><input value={state.internship.organization} onChange={e => setState({ ...state, internship: { ...state.internship, organization: e.target.value } })} /></Field></section><section className="panel"><h3>Dữ liệu cục bộ</h3><p>Mọi thay đổi đang được lưu trong trình duyệt này. Không có tệp nào được gửi sang bên thứ ba.</p><button className="secondary-btn" onClick={() => confirm("Thay dữ liệu hiện tại bằng dữ liệu demo?") && setState(resetState(true))}>Nạp lại dữ liệu demo</button><button className="danger-btn" onClick={() => confirm("Xoá toàn bộ dữ liệu trên thiết bị này?") && setState(resetState(false))}>Xoá dữ liệu và bắt đầu trống</button></section></div></>; }
function Soon({ view }: { view: View }) { const names: Record<string, string> = { references: "Tài liệu tham khảo", appendices: "Phụ lục", preview: "Xem trước tài liệu" }; return <><Title eyebrow="PHASE 2" title={names[view]} desc="Cấu trúc dữ liệu đã sẵn sàng; tính năng tài liệu sẽ được triển khai ở giai đoạn kế tiếp." /><div className="coming"><span>⌁</span><h2>Đã có trong lộ trình Phase 2</h2><p>Preview A4, Compliance Check hoàn chỉnh, xuất Word và PDF sẽ dùng cùng dữ liệu Phase 1.</p><a href="/">Về Tổng quan</a></div></>; }
function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? "field wide" : "field"}><span>{label}</span>{children}</label>; }
function Sensitive({ checked, onChange }: { checked: boolean; onChange: (v: boolean) => void }) { return <label className="sensitive-check wide"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span><b>Đánh dấu dữ liệu nhạy cảm</b><small>Yêu cầu ẩn danh trước khi xuất hoặc dùng AI.</small></span></label>; }
function Empty({ text }: { text: string }) { return <div className="empty"><span>＋</span><p>{text}</p></div>; }
function Modal({ title, onClose, onSubmit, footer, children }: { title: string; onClose: () => void; onSubmit: () => void; footer: string; children: React.ReactNode }) { return <div className="modal-back"><form className="modal" onSubmit={e => { e.preventDefault(); onSubmit(); }}><div className="modal-head"><div><small>NHẬT KÝ THỰC TẬP</small><h2>{title}</h2></div><button type="button" onClick={onClose}>×</button></div>{children}<div className="modal-foot"><span>● {footer}</span><button type="button" className="ghost-btn" onClick={onClose}>Huỷ</button><button className="primary-btn">Lưu</button></div></form></div>; }
